version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=12345N@m
    ports:
      - "1443:1433"
    networks:
      - mynetwork

  springboot:
    build: .
    container_name: springboot-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;encrypt=true;trustServerCertificate=true;databaseName=master
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=12345N@m
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=12345N@m
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    command: [ "redis-server", "--requirepass", "12345N@m" ]

networks:
  mynetwork:
    driver: bridge

