name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4  # Checkout mã nguồn vào thư mục gốc của repository.

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Sử dụng working-directory để đảm bảo các lệnh npm được thực thi trong thư mục frontend.
    - name: Install dependencies
      run: npm ci
      working-directory: Frontend  # Chạy npm ci trong thư mục frontend, nơi có package-lock.json.

    - name: Build project
      run: npm run build --if-present
      working-directory: Frontend  # Build trong thư mục frontend.

    - name: Run tests
      run: npm test
      working-directory: Frontend  # Chạy test trong thư mục frontend.
