name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: Frontend

    - name: Set up Xvfb (X virtual framebuffer)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &
      
    - name: Build the project
      run: npm run build --if-present
      working-directory: Frontend

    - name: Run tests
      run: npm test
      working-directory: Frontend
