name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4  # Bước đầu tiên: checkout mã nguồn vào repository.
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change directory to Frontend
      run: cd Frontend  # Chuyển vào thư mục Frontend
    
    - run: npm ci  # Cài đặt dependencies
      working-directory: Frontend  # Đảm bảo npm ci được chạy trong thư mục Frontend

    - run: npm run build --if-present  # Build project nếu có lệnh build
      working-directory: Frontend  # Đảm bảo build được thực hiện trong thư mục Frontend

    - run: npm test  # Chạy các bài kiểm tra
      working-directory: Frontend  # Đảm bảo tests chạy trong thư mục Frontend
